#########################################################################
# Local stubs for pymad (module name: mad).
#########################################################################

MODE_SINGLE_CHANNEL: int
MODE_DUAL_CHANNEL: int
MODE_JOINT_STEREO: int
MODE_STEREO: int

LAYER_I: int
LAYER_II: int
LAYER_III: int

EMPHASIS_NONE: int
EMPHASIS_50_15_US: int
EMPHASIS_CCITT_J_17: int

class MadFile:
    def __init__(self, filename: str) -> None: ...
    def read(self) -> bytearray | None: ...
    def samplerate(self) -> int: ...
    def mode(self) -> int: ...
    def bitrate(self) -> int: ...
    def layer(self) -> int: ...
    def emphasis(self) -> int: ...
    def current_time(self) -> int: ...
    def total_time(self) -> int: ...
    def seek_time(self, ms: int) -> None: ...
